### ISSUE TITLE
  File "/home/mona/XMem/inference/interact/resource_manager.py", line 171, in _extract_frames     bar = progressbar.ProgressBar(max_value=progressbar.UnknownLength) TypeError: ProgressBar.__init__() got an unexpected keyword argument 'max_value'

### ISSUE THREAD

**Issue by monajalal** [hkchengrex/XMem#124]
I changed the input arg to get an rgb vs depth video input but that's about it. I am not sure why I get this error. Do you know how to fix it?

```
(xmem) (xmem) mona@mona-ThinkStation-P7:~/XMem$ python  interactive_demo.py  --rgb_video /home/mona/XMem/input_vids/raccoon.mp4 --num_objects 1
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
rgb_video is:  /home/mona/XMem/input_vids/raccoon.mp4
depth_vide is:  None
rgb path base: raccoon.mp4
basename: rac
workspace path:   ./workspace/rac
Workspace is in: ./workspace/rac
rgb vid not none
self.depth_image_dir: ./workspace/rac/depth_images
rgb_image_dir ******************: ./workspace/rac/rgb_images
depth_image_dir: ./workspace/rac/depth_images
########################################################
depth doesn't need decoding
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
rgb video inside if is:  /home/mona/XMem/input_vids/raccoon.mp4
Extracting frames from /home/mona/XMem/input_vids/raccoon.mp4 into ./workspace/rac/rgb_images...
Traceback (most recent call last):
  File "/home/mona/XMem/interactive_demo.py", line 94, in <module>
    resource_manager = ResourceManager(config)
  File "/home/mona/XMem/inference/interact/resource_manager.py", line 136, in __init__
    self._extract_frames(rgb_video, self.rgb_image_dir)
  File "/home/mona/XMem/inference/interact/resource_manager.py", line 171, in _extract_frames
    bar = progressbar.ProgressBar(max_value=progressbar.UnknownLength)
TypeError: ProgressBar.__init__() got an unexpected keyword argument 'max_value'
```
after running the command and getting error:
```
(xmem) (xmem) mona@mona-ThinkStation-P7:~/XMem$ ls workspace/
total 12K
drwxrwxr-x  5 mona mona 4.0K Oct 10 09:29 rac
drwxrwxr-x 13 mona mona 4.0K Oct 10 09:29 ..
drwxrwxr-x  3 mona mona 4.0K Oct 10 09:29 .
(xmem) (xmem) mona@mona-ThinkStation-P7:~/XMem$ ls workspace/rac
total 20K
drwxrwxr-x 2 mona mona 4.0K Oct 10 09:29 rgb_images
drwxrwxr-x 2 mona mona 4.0K Oct 10 09:29 masks
drwxrwxr-x 2 mona mona 4.0K Oct 10 09:29 depth_images
drwxrwxr-x 3 mona mona 4.0K Oct 10 09:29 ..
drwxrwxr-x 5 mona mona 4.0K Oct 10 09:29 .
(xmem) (xmem) mona@mona-ThinkStation-P7:~/XMem$ ls workspace/rac/rgb_images/
total 8.0K
drwxrwxr-x 5 mona mona 4.0K Oct 10 09:29 ..
drwxrwxr-x 2 mona mona 4.0K Oct 10 09:29 .


(xmem) (xmem) mona@mona-ThinkStation-P7:~/XMem$ ls workspace/rac/depth_images/
total 8.0K
drwxrwxr-x 5 mona mona 4.0K Oct 10 09:29 ..
drwxrwxr-x 2 mona mona 4.0K Oct 10 09:29 .

```

**Comment by monajalal** [comment]
my bad, problem was resolved by installing progressbar2 instead of progressbar
