### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by juneleung** [hkchengrex/XMem#35]
I try to run with GUI but looks failed:
```
C:\Users\84703\Downloads\XMem>python interactive_demo.py --video demo\test.mp4 --num_objects 4
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Workspace is in: ./workspace\test
Extracting frames from demo\test.mp4 into ./workspace\test\images...
Traceback (most recent call last):
  File "interactive_demo.py", line 91, in <module>
    resource_manager = ResourceManager(config)
  File "C:\Users\84703\Downloads\XMem\inference\interact\resource_manager.py", line 85, in __init__
    self._extract_frames(video)
  File "C:\Users\84703\Downloads\XMem\inference\interact\resource_manager.py", line 107, in _extract_frames
    bar = progressbar.ProgressBar(max_value=progressbar.UnknownLength)
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

**Comment by hkchengrex** [comment]
Are you sure you have installed `progressbar2`, not `progressbar`?

**Comment by juneleung** [comment]
Thanks, it works! :)
