### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by Eliza-wxq** [hkchengrex/XMem#53]
(Xmen) user3@gpu-serv01:/work/user3/wxq/XMem-main$  CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.run --master_port 25763 --nproc_per_node=2 train
.py --exp_id retrain --stage 03

WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable
 for optimal performance in your application as needed.
*****************************************
/home/user3/.conda/envs/Xmen/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu
.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
/home/user3/.conda/envs/Xmen/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu
.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
CUDA Device count: 2
CUDA Device count: 2
I am rank 0 in this world of size 2!
We are assuming 2 GPUs.
We are now starting stage 0
I will take the role of logging!
Traceback (most recent call last):
  File "/media/SSD/user3/wxq/XMem-main/train.py", line 81, in <module>
    logger = TensorboardLogger(config['exp_id'], long_id, git_info)
NameError: name 'git_info' is not defined
I am rank 1 in this world of size 2!
We are assuming 2 GPUs.
We are now starting stage 0
Single object mode: True
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3226564 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3226563) of binary: /home/user3/.conda/envs/Xmen/bin/python
Traceback (most recent call last):
  File "/home/user3/.conda/envs/Xmen/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user3/.conda/envs/Xmen/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user3/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 728, in <module>
    main()
  File "/home/user3/.local/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/user3/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/user3/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/user3/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user3/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-26_13:52:15
  host      : gpu-serv01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3226563)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

How can I solve this mistake?

**Comment by hkchengrex** [comment]
You might have changed something (e.g., removed `git_info`), as `logger = TensorboardLogger(config['exp_id'], long_id, git_info)` is on line 82 in our code but on line 81 in your error message.
