### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by chenttt2001** [hkchengrex/XMem#54]
(XMem) xwh@ubuntu:~/CJQ/XMem-main/XMem-main$ CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.run --master_port 25763 --nproc_per_node=2 train.py --exp_id retrain --stage 03

WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
CUDA Device count: 2
CUDA Device count: 2
Traceback (most recent call last):
  File "/data/xwh/CJQ/XMem-main/XMem-main/train.py", line 36, in <module>
    repo = git.Repo(".")
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/git/repo/base.py", line 266, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/git/repo/base.py", line 347, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
Traceback (most recent call last):
  File "/data/xwh/CJQ/XMem-main/XMem-main/train.py", line 36, in <module>
    repo = git.Repo(".")
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/git/repo/base.py", line 266, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/git/repo/base.py", line 347, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2459722) of binary: /data/xwh/anaconda3/envs/XMem/bin/python
Traceback (most recent call last):
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/xwh/anaconda3/envs/XMem/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-12-26_18:53:41
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2459723)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-26_18:53:41
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2459722)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

How can I solve this problem?

**Comment by hkchengrex** [comment]
See https://github.com/hkchengrex/XMem/issues/20

**Comment by chenttt2001** [comment]
thanks
