### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_value'

### ISSUE THREAD

**Issue by ToniButland1998** [hkchengrex/XMem#78]
./saves/XMem-s012.pth
480
1
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Workspace is in: ./workspace/24
Extracting frames from source/24.mp4 into ./workspace/24/images...
Traceback (most recent call last):
  File "interactive_demo.py", line 167, in <module>
    resource_manager = ResourceManager(config)
  File "/data5/XMem/inference/interact/resource_manager.py", line 85, in __init__
    self._extract_frames(video)
  File "/data5/XMem/inference/interact/resource_manager.py", line 107, in _extract_frames
    bar = progressbar.ProgressBar(max_value=progressbar.UnknownLength)
TypeError: __init__() got an unexpected keyword argument 'max_value'

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/XMem/issues/35
